Update dotfiles for ubuntu i3 setup

diff --git a/private_dot_config/tmux/plugins/t-smart-tmux-session-manager/bin/executable_t b/private_dot_config/tmux/plugins/t-smart-tmux-session-manager/bin/executable_t
--- a/private_dot_config/tmux/plugins/t-smart-tmux-session-manager/bin/executable_t
+++ b/private_dot_config/tmux/plugins/t-smart-tmux-session-manager/bin/executable_t
@@ -83,42 +83,98 @@ get_fzf_find_binding() {
 	fi
 	[ -n "$fzf_find_binding" ] && echo "$fzf_find_binding" || echo "$fzf_find_binding_default"
 }
+
 FIND_BIND=$(get_fzf_find_binding)
 
-BORDER_LABEL=" t - smart tmux session manager "
+get_sessions_by_mru() {
+	if [ "$T_RUNTYPE" == "attached" ]; then
+		CURRENT_SID=$(tmux display-message -p "#{session_id}")
+	else
+		CURRENT_SID=""
+	fi
+	tmux list-sessions \
+		-f "#{!=:#{session_id},$CURRENT_SID}" \
+		-F '#{session_last_attached} #{session_name}' \
+		| sort --numeric-sort --reverse | awk '{print $2}; END {print "———"}'
+}
+
+get_zoxide_results() {
+	zoxide query -l | sed -e "$HOME_REPLACER"
+}
+
+get_fzf_results() {
+	if [ "$TMUX_RUNNING" -eq 0 ]; then
+		fzf_default_results="$(tmux show -gqv '@t-fzf-default-results')"
+		case $fzf_default_results in
+		sessions)
+			get_sessions_by_mru
+			;;
+		zoxide)
+			get_zoxide_results
+			;;
+		*)
+			get_sessions_by_mru && get_zoxide_results # default shows both
+			;;
+		esac
+	else
+		get_zoxide_results # only show zoxide results when outside tmux
+	fi
+}
+
+fzf_border_label_default=' t - smart tmux session manager '
+BORDER_LABEL=${T_FZF_BORDER_LABEL:-$fzf_border_label_default}
+
 HEADER=" ^s sessions ^x zoxide ^f find"
 SESSION_BIND="ctrl-s:change-prompt(sessions> )+reload(tmux list-sessions -F '#S')"
 ZOXIDE_BIND="ctrl-x:change-prompt(zoxide> )+reload(zoxide query -l | sed -e \"$HOME_REPLACER\")"
 TAB_BIND="tab:down,btab:up"
 
-get_sessions_by_mru() {
-	tmux list-sessions -F '#{session_last_attached} #{session_name}' | sort --numeric-sort --reverse | awk '{print $2}'
-}
-
-if [ $# -eq 1 ]; then # argument provided
-	zoxide query "$1" &>/dev/null
-	ZOXIDE_RESULT_EXIT_CODE=$?
-	if [ $ZOXIDE_RESULT_EXIT_CODE -eq 0 ]; then # zoxide result found
-		RESULT=$(zoxide query "$1")
-	else # no zoxide result found
-		ls "$1" &>/dev/null
-		LS_EXIT_CODE=$?
-		if [ $LS_EXIT_CODE -eq 0 ]; then # directory found
-			RESULT=$1
-		else # no directory found
-			echo "No directory found."
+if [ $# -ge 1 ]; then # argument provided
+	if [ "$1" = "-r" ] || [ "$1" == "--repo" ]; then
+		if [[ -z $T_REPOS_DIR ]]; then
+			echo "T_REPOS_DIR has not been set"
 			exit 1
+		fi
+
+		if [ -z "$2" ]; then
+			echo "No repository url provided -r {url}"
+			exit 1
+		fi
+
+		REPO_URL=$2
+		cd $T_REPOS_DIR
+
+		if git clone --recursive $REPO_URL; then
+			RESULT="$T_REPOS_DIR/$(basename "$_" .git)"
+		else
+			exit $? # exit code from last command
+		fi
+
+	else # not -r or --repo
+		zoxide query "$1" &>/dev/null
+		ZOXIDE_RESULT_EXIT_CODE=$?
+		if [ $ZOXIDE_RESULT_EXIT_CODE -eq 0 ]; then # zoxide result found
+			RESULT=$(zoxide query "$1")
+		else # no zoxide result found
+			ls "$1" &>/dev/null
+			LS_EXIT_CODE=$?
+			if [ $LS_EXIT_CODE -eq 0 ]; then # directory found
+				RESULT=$1
+			else # no directory found
+				echo "No directory found."
+				exit 1
+			fi
 		fi
 	fi
 else # argument not provided
 	case $T_RUNTYPE in
 	attached)
-		if [[ ! -v $FZF_TMUX_OPTS ]]; then
+		if [[ -z $FZF_TMUX_OPTS ]]; then
 			FZF_TMUX_OPTS="-p 53%,58%"
 		fi
 
 		RESULT=$(
-			(get_sessions_by_mru && (zoxide query -l | sed -e "$HOME_REPLACER")) | fzf-tmux \
+			(get_fzf_results) | fzf-tmux \
 				--bind "$FIND_BIND" \
 				--bind "$SESSION_BIND" \
 				--bind "$TAB_BIND" \
@@ -132,11 +188,12 @@ else # argument not provided
 		;;
 	detached)
 		RESULT=$(
-			(get_sessions_by_mru && (zoxide query -l | sed -e "$HOME_REPLACER")) | fzf \
+			(get_fzf_results) | fzf \
 				--bind "$FIND_BIND" \
 				--bind "$SESSION_BIND" \
 				--bind "$TAB_BIND" \
 				--bind "$ZOXIDE_BIND" \
+				--border \
 				--border-label "$BORDER_LABEL" \
 				--header "$HEADER" \
 				--no-sort \
@@ -145,11 +202,13 @@ else # argument not provided
 		;;
 	serverless)
 		RESULT=$(
-			(zoxide query -l | sed -e "$HOME_REPLACER") | fzf \
+			(get_fzf_results) | fzf \
 				--bind "$FIND_BIND" \
 				--bind "$TAB_BIND" \
+				--bind "$ZOXIDE_BIND" \
+				--border \
 				--border-label "$BORDER_LABEL" \
-				--header " ^f find" \
+				--header " ^x zoxide ^f find" \
 				--no-sort \
 				--prompt "$PROMPT"
 		)
@@ -167,7 +226,29 @@ fi
 
 zoxide add "$RESULT" &>/dev/null # add to zoxide database
 
-if [[ $T_SESSION_NAME_INCLUDE_PARENT == 'true' ]]; then
+if [[ $RESULT != /* ]]; then # not folder path from zoxide result
+	SESSION_NAME=$RESULT
+elif [[ $T_SESSION_USE_GIT_ROOT == 'true' ]]; then
+	GIT_ROOT=$(git -C $RESULT rev-parse --show-toplevel 2>/dev/null) && echo $GIT_ROOT >/dev/null
+	if [[ $? -ne 0 ]]; then # not inside git repository
+		SESSION_NAME=$(basename "$RESULT" | tr ' .:' '_')
+	else # is in git repository
+		BASENAME=$(basename $GIT_ROOT)
+		RELATIVE_PATH=${RESULT#$GIT_ROOT}
+
+		# git worktree
+		GIT_WORKTREE_ROOT=$(git -C $RESULT rev-parse --git-common-dir 2>/dev/null) && echo $GIT_WORKTREE_ROOT >/dev/null
+		if [[ $? -eq 0 ]] && [[ ! $GIT_WORKTREE_ROOT =~ ^(\.\./)*\.git$ ]]; then # is inside git worktree
+			GIT_WORKTREE_ROOT=$(echo $GIT_WORKTREE_ROOT | sed -E 's/(\/.git|\/.bare)$//') # remove .git or .bare suffix
+			BASENAME=$(basename $GIT_WORKTREE_ROOT)
+			RELATIVE_PATH=${RESULT#$GIT_WORKTREE_ROOT}
+		fi
+
+		SEPARATOR="/"
+		FORMATTED_PATH="${RELATIVE_PATH//\//$SEPARATOR}"
+		SESSION_NAME=$(echo $BASENAME$FORMATTED_PATH | tr ' .:' '_')
+	fi
+elif [[ $T_SESSION_NAME_INCLUDE_PARENT == 'true' ]]; then
 	SESSION_NAME=$(echo "$RESULT" | tr ' .:' '_' | awk -F "/" '{print $(NF-1)"/"$NF}')
 else
 	SESSION_NAME=$(basename "$RESULT" | tr ' .:' '_')
@@ -179,15 +260,18 @@ fi
 
 if [ "$SESSION" = "" ]; then # session is missing
 	SESSION="$SESSION_NAME"
-	tmux new-session -d -s "$SESSION" -c "$RESULT" # create session
+	if [ -e $RESULT/.t ]; then
+		tmux new-session -d -s "$SESSION" -c "$RESULT" $RESULT/.t # create session and run .t startup script
+	else
+		tmux new-session -d -s "$SESSION" -c "$RESULT" # create session
+	fi
 fi
 
 case $T_RUNTYPE in # attach to session
 attached)
 	tmux switch-client -t "$SESSION"
 	;;
-detached) ;&
-serverless)
+detached | serverless)
 	tmux attach -t "$SESSION"
 	;;
 esac
diff --git a/private_dot_config/tmux/plugins/tmux-nerd-font-window-name/bin/executable_tmux-nerd-font-window-name b/private_dot_config/tmux/plugins/tmux-nerd-font-window-name/bin/executable_tmux-nerd-font-window-name
--- a/private_dot_config/tmux/plugins/tmux-nerd-font-window-name/bin/executable_tmux-nerd-font-window-name
+++ b/private_dot_config/tmux/plugins/tmux-nerd-font-window-name/bin/executable_tmux-nerd-font-window-name
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 
+if ! command -v yq >/dev/null 2>&1; then
+	echo "$1 ⚠︎ yq missing"
+	exit 1
+fi
+
 NAME="$1"
+PANES="$2"
 CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 DEFAULT_CONFIG="$CURRENT_DIR/defaults.yml"
 USER_CONFIG="$HOME/.config/tmux/tmux-nerd-font-window-name.yml"
@@ -19,16 +25,28 @@ get_config_value() {
 	echo "$value"
 }
 
-ICON="$(get_config_value ".icons.$NAME")"
+ICON="$(get_config_value ".icons.\"$NAME\"")"
 
 if [ "$ICON" == "null" ]; then
 	FALLBACK_ICON="$(get_config_value '.config.fallback-icon')"
 	ICON="$FALLBACK_ICON"
 fi
 
+if [ "$PANES" -gt 1 ]; then
+	MULTI_PANE_ICON="$(get_config_value '.config.multi-pane-icon')"
+	if [ "$MULTI_PANE_ICON" != "null" ]; then
+		ICON="$MULTI_PANE_ICON $ICON"
+	fi
+fi
+
 SHOW_NAME="$(get_config_value '.config.show-name')"
 if [ "$SHOW_NAME" = true ]; then
-	ICON="$ICON $NAME"
+	ICON_POSITION="$(get_config_value '.config.icon-position')"
+	if [ "$ICON_POSITION" == "right" ]; then
+		ICON="$NAME $ICON"
+	else
+		ICON="$ICON $NAME"
+	fi
 fi
 
 echo "$ICON"
